In [1]:
import numpy as np
import matplotlib.pyplot as plt
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [3]:
M1 = 3.91010277E-09
M2 =2.73151622E-04
M3 = 3.64415977E-04 

S2Sun = 0.323                                                         #S2Sun: Sino square sun angle 
S2Atm = 0.573                                                         #S2Atm: Sino square atmospheric angle 
S2Rea = 0.0229                                                        #S2Rea: Sino square reactor angle 

ThetSun = np.arcsin(np.sqrt(S2Sun))                               #ThetSun: Sun Angle theta12
ThetAtm = np.arcsin(np.sqrt(S2Atm))                               #ThetAtm: Atmospheric Angle theta23
ThetRea = np.arcsin(np.sqrt(S2Rea))                               #ThetRea: Reactor Angle theta13

print ThetSun*180/np.pi
print ThetAtm*180/np.pi
print ThetRea*180/np.pi


34.6339154306
49.1975956283
8.70386261152


In [4]:
Mv = np.matrix( [[M1,0.,0],[0.,M2,0.],[0.,0.,M3]] )               #Mv: Mass Matrix diag  
USun = np.matrix( [[np.cos(ThetSun),np.sin(ThetSun),0.],[-np.sin(ThetSun),np.cos(ThetSun),0.],[0.,0.,1.]] )
UAtm = np.matrix( [[1.,0.,0.],[0.,np.cos(ThetAtm),-np.sin(ThetAtm)],[0.,np.sin(ThetAtm),np.cos(ThetAtm)]] )
URea = np.matrix( [[np.cos(ThetRea),0.,np.sin(ThetRea)],[0.,1.,0.],[-np.sin(ThetRea),0.,np.cos(ThetRea)]] )
U = UAtm*URea*USun                                                #U: Rotation Matrix
UT = np.matrix.transpose(U)                                       #UT: Transpose rotation Matrix


In [5]:
M = UT*Mv*U                                                       #M: Matrix no diag
Eig,Me = np.linalg.eig(M)                                         #Eig:Eigenvalues of M and Me:Euigenvector of M
n = np.argsort(np.abs(Eig))                                       
Eig = np.array([Eig[n[0]],Eig[n[1]],Eig[n[2]]])
Mn = np.asarray(np.hstack((Me[:,n[0]],Me[:,n[1]],Me[:,n[2]])))    #Mn: Eigenvector matrix sorting

print Eig
print Mn

[  3.91010277e-09   2.73151622e-04   3.64415977e-04]
[[ 0.81332447  0.27712542  0.51157091]
 [ 0.56178581 -0.60276297 -0.56663348]
 [ 0.15132746  0.74825016 -0.64592701]]


In [6]:
f12 = 1.00000000E-02
f13 = 0.00000000E-00
f23 = 3.00000000E-01

O11 = 1.00000000E-04
O21 = 3.00000000E-03
O31 = 3.00000000E-03

O12 = 3.00000000E-03
O22 = 1.00000000E-02
O32 = 3.00000000E-03

O13 = 3.00000000E-03
O23 = 3.00000000E-03
O33 = 1.00000000E-02


O = np.matrix( [[O11,O21,O31],[O12,O22,O32],[O13,O23,O33]] ) 
OT = np.matrix.transpose(O)   
F = np.matrix( [[0.,f12,f13],[-f12,0.,f23],[-f13,-f23,0.]] )
FT = np.matrix.transpose(F)   
Mk = FT*Mv*O + OT*Mv*F 

Eig1,Me1 = np.linalg.eig(Mk)                                         #Eig:Eigenvalues of M and Me:Euigenvector of M
j = np.argsort(np.abs(Eig1))                                       
Eig1 = np.array([Eig1[j[0]],Eig1[j[1]],Eig1[j[2]]])
Mn1 = np.asarray(np.hstack((Me1[:,j[0]],Me1[:,j[1]],Me1[:,j[2]]))) 

print Eig1

[ -4.74938942e-08   7.00385994e-07  -8.33556801e-07]
