In [1]:
import numpy as np
import matplotlib.pyplot as plt
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [3]:
M1 = 3.91010277E-09
M2 =2.73151622E-04
M3 = 3.64415977E-04 

S2Sun = 0.323                                                         #S2Sun: Sino square sun angle 
S2Atm = 0.573                                                         #S2Atm: Sino square atmospheric angle 
S2Rea = 0.0229                                                        #S2Rea: Sino square reactor angle 

ThetSun = np.arcsin(np.sqrt(S2Sun))                               #ThetSun: Sun Angle theta12
ThetAtm = np.arcsin(np.sqrt(S2Atm))                               #ThetAtm: Atmospheric Angle theta23
ThetRea = np.arcsin(np.sqrt(S2Rea))                               #ThetRea: Reactor Angle theta13

print ThetSun*180/np.pi
print ThetAtm*180/np.pi
print ThetRea*180/np.pi


34.6339154306
49.1975956283
8.70386261152


In [4]:
Mv = np.matrix( [[M1,0.,0],[0.,M2,0.],[0.,0.,M3]] )               #Mv: Mass Matrix diag  
USun = np.matrix( [[np.cos(ThetSun),np.sin(ThetSun),0.],[-np.sin(ThetSun),np.cos(ThetSun),0.],[0.,0.,1.]] )
UAtm = np.matrix( [[1.,0.,0.],[0.,np.cos(ThetAtm),-np.sin(ThetAtm)],[0.,np.sin(ThetAtm),np.cos(ThetAtm)]] )
URea = np.matrix( [[np.cos(ThetRea),0.,np.sin(ThetRea)],[0.,1.,0.],[-np.sin(ThetRea),0.,np.cos(ThetRea)]] )
U = UAtm*URea*USun                                                #U: Rotation Matrix
UT = np.matrix.transpose(U)                                       #UT: Transpose rotation Matrix


In [5]:
M = UT*Mv*U                                                       #M: Matrix no diag
Eig,Me = np.linalg.eig(M)                                         #Eig:Eigenvalues of M and Me:Euigenvector of M
n = np.argsort(np.abs(Eig))                                       
Eig = np.array([Eig[n[0]],Eig[n[1]],Eig[n[2]]])
Mn = np.asarray(np.hstack((Me[:,n[0]],Me[:,n[1]],Me[:,n[2]])))    #Mn: Eigenvector matrix sorting

print Eig
print Mn

[  3.91010277e-09   2.73151622e-04   3.64415977e-04]
[[ 0.81332447  0.27712542  0.51157091]
 [ 0.56178581 -0.60276297 -0.56663348]
 [ 0.15132746  0.74825016 -0.64592701]]


In [25]:
mu=1.0000000E+02  # Muinput
v=246.2
Mc1=9.92358293E+01  # Hm_2
Mc2=1.41455019E+03 
sin2phi=np.sqrt(2.)*v*mu/(Mc2**2-Mc1**2)
k=sin2phi*np.log(Mc2**2/Mc1**2)/(4.*np.pi)**2
me=5.10998930E-04  # Fe_1
mmu=1.05658372E-01  # Fe_2
mtau=1.77669000E+00  # Fe_3
Ml=np.matrix(np.diag([me,mmu,mtau]))

f12 = 1.00000000E-02
f13 = 0.00000000E-00
f23 = 3.00000000E-01

O11 = 1.00000000E-04
O21 = 3.00000000E-03
O31 = 3.00000000E-03

O12 = 3.00000000E-03
O22 = 1.00000000E-02
O32 = 3.00000000E-03

O13 = 3.00000000E-03
O23 = 3.00000000E-03
O33 = 1.00000000E-02


O = np.matrix( [[O11,O21,O31],[O12,O22,O32],[O13,O23,O33]] ) 
OT = np.matrix.transpose(O)   
F = np.matrix( [[0.,f12,f13],[-f12,0.,f23],[-f13,-f23,0.]] )
FT = np.matrix.transpose(F)   
Mk =k*( FT*Ml*O + OT*Ml*F )

Eig1,Me1 = np.linalg.eig(Mk)                                         #Eig:Eigenvalues of M and Me:Euigenvector of M
j = np.argsort(np.abs(Eig1))                                       
Eig1 = np.array([Eig1[j[0]],Eig1[j[1]],Eig1[j[2]]])
Mn1 = np.asarray(np.hstack((Me1[:,j[0]],Me1[:,j[1]],Me1[:,j[2]]))) 

print Eig1

[ -2.44326129e-08   2.38334502e-06  -4.13264858e-06]


In [14]:
cat SPheno.spc.Zee | grep -i -A20 'block mass'

Block MASS  # Mass spectrum
#   PDG code      mass          particle
        25     1.25708286E+02  # hh_1
        35     1.41448166E+03  # hh_2
        36     1.40374062E+03  # Ah_2
        37     9.92358293E+01  # Hm_2
    900037     1.41455019E+03  # Hm_3
        23     9.11887000E+01  # VZ
        24     8.03497269E+01  # VWm
         1     5.00000000E-03  # Fd_1
         3     9.50000000E-02  # Fd_2
         5     4.18000000E+00  # Fd_3
         2     2.50000000E-03  # Fu_1
         4     1.27000000E+00  # Fu_2
         6     1.73500000E+02  # Fu_3
        11     5.10998930E-04  # Fe_1
        13     1.05658372E-01  # Fe_2
        15     1.77669000E+00  # Fe_3
        12    -3.91010277E-09  # Fv_1
        14     2.73151622E-04  # Fv_2
        16    -3.64415977E-04  # Fv_3


In [15]:
cat LesHouches.in.Zee

BLOCK MODSEL
   1   1              #  1/0: High/low scale input 
   2   1              # Boundary Condition  
   6   1              # Generation Mixing 

BLOCK SMINPUTS
   2   1.166370E-05   # G_F,Fermi constant 
   3   1.187000E-01   # alpha_s(MZ) SM MSbar 
   4   9.118870E+01   # Z-boson pole mass 
   5   4.180000E+00   # m_b(mb) SM MSbar 
   6   1.735000E+02   # m_top(pole) 
   7   1.776690E+00   # m_tau(pole) 

BLOCK MINPAR
   1   1.0000000E-01  # Lambda1Input
   2   1.3000000E-01  # Lambda2Input
   3   1.1000000E+00  # Lambda3Input
   4   -5.0000000E-01 # Lambda4Input
   5   5.0000000E-01  # Lambda5Input
   6   0.000000E+00   # Lambda6Input
   7   0.000000E+00   # Lambda7Input
   8   0.000000E+00   # Lambda8Input
   9   0.000000E+00   # Lambda9Input
   10   0.000000E+00   # Lambda10Input
   11   0.000000E+00   # LambdahInput
   12   4.0000000E+04  # M12input
   13   1.0000000E+04  # Mhinput
   14   1.0000000E+02  # Muinput
   15   5.0000000E+01  # TanBeta

BLOCK SPHENOINPUT
   1  